# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 13:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FITSFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fits_filename', models.CharField(max_length=255)),
                ('catalogue_filename', models.CharField(max_length=255)),
                ('process_status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('HEADER', 'Header check'), ('OBSERVATION', 'Add observation details'), ('ASTROMETRY', 'Astrometry'), ('PHOTOMETRY', 'Photometry'), ('CALIBRATION', 'Calibration'), ('COMPLETE', 'Processing complete'), ('FAILED', 'Processing failed'), ('FAILED_USER', 'User invoked processing failed'), ('CHECK_ASTROMETRY', 'Check whether astrometry was successful'), ('CHECK_PHOTOMETRY', 'Check whether astrometry was successful'), ('CHECK_CALIBRATION', 'Check whether astrometry was successful')], max_length=255)),
                ('upload_time', models.IntegerField()),
                ('header', models.CharField(max_length=10000)),
                ('sha256', models.CharField(max_length=64)),
                ('uuid', models.UUIDField()),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fits_files',
            },
        ),
        migrations.CreateModel(
            name='ImagingDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('scale', models.FloatField()),
                ('date_card', models.CharField(blank=True, max_length=9, null=True)),
                ('filter_card', models.CharField(blank=True, max_length=9, null=True)),
                ('exptime_card', models.CharField(blank=True, max_length=9, null=True)),
                ('date_format', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'imaging_devices',
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('ra', models.CharField(max_length=255)),
                ('dec', models.CharField(max_length=255)),
                ('cal_offset', models.FloatField()),
            ],
            options={
                'db_table': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField(blank=True, null=True)),
                ('filter', models.CharField(blank=True, max_length=255, null=True)),
                ('exptime', models.FloatField(blank=True, null=True)),
                ('detected_stars', models.IntegerField(blank=True, null=True)),
                ('limiting_magnitude', models.FloatField(blank=True, null=True)),
                ('detected_stars_calibration', models.FloatField(blank=True, null=True)),
                ('med_offset', models.FloatField(blank=True, null=True)),
                ('calibration_parameters', models.CharField(blank=True, max_length=255, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.ImagingDevice')),
                ('fits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.FITSFile')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Object')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'observations',
            },
        ),
        migrations.CreateModel(
            name='Photometry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibrated_magnitude', models.FloatField()),
                ('calibrated_error', models.FloatField()),
                ('magnitude_rms_error', models.FloatField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('alpha_j2000', models.FloatField()),
                ('delta_j2000', models.FloatField()),
                ('fwhm_world', models.FloatField()),
                ('flags', models.CharField(max_length=10)),
                ('magnitude', models.FloatField()),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Observation')),
            ],
            options={
                'db_table': 'photometry',
            },
        ),
    ]
