# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_squashed_0019_auto_20170705_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitsfile',
            name='catalogue_filename',
            field=models.CharField(max_length=255),
        ),
    ]
