# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unprocessedupload',
            name='id',
        ),
        migrations.AlterField(
            model_name='unprocessedupload',
            name='uuid',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
