# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagingdevice',
            name='description',
            field=models.CharField(default='', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagingdevice',
            name='mirror_diameter',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagingdevice',
            name='mirror_size',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
