# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitsfile',
            name='header',
            field=models.CharField(max_length=10000),
        ),
        migrations.DeleteModel(
            name='FITSHeader',
        ),
    ]
