# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20170629_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unprocessedupload',
            name='upload_time',
            field=models.IntegerField(),
        ),
    ]
