# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 13:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analysis', '0002_auto_20170710_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagingDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('naxis1', models.IntegerField()),
                ('naxis2', models.IntegerField()),
                ('scale', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
