# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20170719_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='time',
            new_name='date',
        ),
    ]
