# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 15:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analysis', '0003_auto_20170629_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fits_file', models.FilePathField()),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('header', models.CharField(max_length=10000)),
                ('filter', models.CharField(max_length=10)),
                ('fits_file', models.FilePathField()),
                ('cat_file', models.FilePathField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'observations',
            },
        ),
        migrations.CreateModel(
            name='Photometry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibrated_magnitude', models.DecimalField(decimal_places=10, max_digits=20)),
                ('magnitude_rms_error', models.DecimalField(decimal_places=10, max_digits=20)),
                ('x', models.DecimalField(decimal_places=10, max_digits=20)),
                ('y', models.DecimalField(decimal_places=10, max_digits=20)),
                ('alpha_j2000', models.DecimalField(decimal_places=10, max_digits=20)),
                ('delta_j2000', models.DecimalField(decimal_places=10, max_digits=20)),
                ('fwhm_world', models.DecimalField(decimal_places=10, max_digits=20)),
                ('flags', models.CharField(max_length=10)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'photometry',
            },
        ),
        migrations.AlterModelTable(
            name='unprocessedupload',
            table='unprocessed_uploads',
        ),
    ]
