# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_auto_20170719_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagingdevice',
            name='mirror_size',
        ),
        migrations.AlterField(
            model_name='imagingdevice',
            name='description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
