# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_auto_20170713_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitsfile',
            name='sha256',
            field=models.CharField(default='9e11eacd1c79bd172dbff7b7db09ef2f037dfaab294c04528a581f4363e21bef', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unprocessedupload',
            name='sha256',
            field=models.CharField(default='9e11eacd1c79bd172dbff7b7db09ef2f037dfaab294c04528a581f4363e21bef', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fitsfile',
            name='process_status',
            field=models.CharField(choices=[('HEADER', 'Header check'), ('OBSERVATION', 'Add observation details'), ('ASTROMETRY', 'Astrometry'), ('PHOTOMETRY', 'Photometry'), ('CALIBRATION', 'Calibration'), ('COMPLETE', 'Processing complete'), ('FAILED', 'Processing failed'), ('FAILED_USER', 'User invoked processing failed'), ('CHECK_ASTROMETRY', 'Check whether astrometry was successful'), ('CHECK_PHOTOMETRY', 'Check whether astrometry was successful'), ('CHECK_CALIBRATION', 'Check whether astrometry was successful')], max_length=255),
        ),
    ]
