# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_auto_20170719_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='orignal_filter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
