# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_auto_20170630_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fitsmeta',
            old_name='catalog_location',
            new_name='catalog_filename',
        ),
        migrations.RenameField(
            model_name='fitsmeta',
            old_name='fits_location',
            new_name='fits_filename',
        ),
    ]
