# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_observation_orignal_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitsfile',
            name='original_filename',
            field=models.CharField(default='no_original_filename_avaliable.fits', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fitsfile',
            name='process_status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('DEVICESETUP', 'Device setup'), ('METADATA', 'Metadata check'), ('OBSERVATION', 'Add observation details'), ('ASTROMETRY', 'Astrometry'), ('PHOTOMETRY', 'Photometry'), ('CALIBRATION', 'Calibration'), ('COMPLETE', 'Processing complete'), ('FAILED', 'Processing failed'), ('FAILED_USER', 'User invoked processing failed'), ('CHECK_ASTROMETRY', 'Check whether astrometry was successful'), ('CHECK_PHOTOMETRY', 'Check whether astrometry was successful'), ('CHECK_CALIBRATION', 'Check whether astrometry was successful')], max_length=255),
        ),
    ]
