# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_auto_20170721_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitsfile',
            name='process_status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('DEVICESETUP', 'Device setup'), ('METADATA', 'Metadata check'), ('OBSERVATION', 'Add observation details'), ('ASTROMETRY', 'Astrometry'), ('CALIBRATION', 'Calibration'), ('COMPLETE', 'Processing complete'), ('FAILED', 'Processing failed'), ('FAILED_USER', 'User invoked processing failed'), ('CHECK_ASTROMETRY', 'Check whether astrometry was successful'), ('CHECK_CALIBRATION', 'Check whether calibration was successful')], max_length=255),
        ),
    ]
