# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_auto_20170630_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitsheader',
            name='airmass',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='aptarea',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='aptdia',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='ast_band',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='ast_cat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='astinst',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='astirms1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='astirms2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='astrrms1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='astrrms2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='bitpix',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='ccd_temp',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='cd1_1',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='cd1_2',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='cd2_1',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='cd2_2',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='cdelt1',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='cdelt2',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='crpix1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='crpix2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='crval1',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='crval2',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='ctype1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='ctype2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='cunit1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='cunit2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='date_obs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='equinox',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='exp_tot',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='exposure',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='exptime',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='filter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='flipstat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='flxscale',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='focallen',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='focuspos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='focussz',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='focustem',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='froupno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='history',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='imagetyp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='instrume',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='jd',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='jd_ave',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='jd_helio',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='magzerop',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='n_stack',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='naxis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='naxis1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='naxis2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='objctalt',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='objctaz',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='objctdec',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='objctha',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='objctra',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='object',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='observer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='photirms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='photlink',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='pierside',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='pv1_0',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='pv1_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='pv1_10',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='pv1_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='pv1_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='pv1_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='pv1_5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='pv1_6',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='pv1_7',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='pv1_8',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='pv1_9',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='pv2_0',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='pv2_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='pv2_10',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='pv2_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='pv2_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='pv2_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='pv2_5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='pv2_6',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='pv2_7',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='pv2_8',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='pv2_9',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='radesys',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='set_temp',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='sitelat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='sitelong',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='swcreate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='swowner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='swserial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='telescop',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='usedbias',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='useddark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='usedflat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='xbinning',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='xorgsubf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='xpixsz',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='ybinning',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='yorgsubf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='ypixsz',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True),
        ),
    ]
