# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-06 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_auto_20170822_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryPhotometry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibrated_magnitude', models.FloatField()),
                ('calibrated_error', models.FloatField()),
                ('magnitude_rms_error', models.FloatField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('alpha_j2000', models.FloatField()),
                ('delta_j2000', models.FloatField()),
                ('fwhm_world', models.FloatField()),
                ('flags', models.CharField(max_length=10)),
                ('magnitude', models.FloatField()),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Observation')),
            ],
            options={
                'db_table': 'photometry_temp',
            },
        ),
    ]
