# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0012_fitsprocessingstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitsmeta',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='fitsprocessingstatus',
            name='file',
        ),
        migrations.RemoveField(
            model_name='fitsfile',
            name='process_stage',
        ),
        migrations.AddField(
            model_name='fitsfile',
            name='process_status',
            field=models.CharField(choices=[('HEADER', 'Header check'), ('ASTROMETRY', 'Astrometry'), ('PHOTOMETRY', 'Photometry'), ('CALIBRATION', 'Calibration'), ('COMPLETE', 'Processing complete')], default='HEADER', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FITSMeta',
        ),
        migrations.DeleteModel(
            name='FITSProcessingStatus',
        ),
    ]
