# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0013_auto_20170703_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('ra', models.CharField(max_length=255)),
                ('dec', models.CharField(max_length=255)),
                ('catalogue_filename', models.FilePathField()),
                ('max_use', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cal_offset', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.RenameField(
            model_name='fitsfile',
            old_name='catalog_filename',
            new_name='catalogue_filename',
        ),
    ]
