# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0014_auto_20170705_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='catalogue_filename',
        ),
    ]
