# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0015_remove_object_catalogue_filename'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='object',
            table='objects',
        ),
    ]
