# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0016_auto_20170705_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='target',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='analysis.Object'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fitsfile',
            name='process_status',
            field=models.CharField(choices=[('HEADER', 'Header check'), ('OBSERVATION', 'Add observation details'), ('ASTROMETRY', 'Astrometry'), ('PHOTOMETRY', 'Photometry'), ('CALIBRATION', 'Calibration'), ('COMPLETE', 'Processing complete')], max_length=255),
        ),
        migrations.AlterField(
            model_name='observation',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
