# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0017_auto_20170705_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='photometry',
            name='magnitude',
            field=models.DecimalField(decimal_places=10, default=1, max_digits=20),
            preserve_default=False,
        ),
    ]
