# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0018_photometry_magnitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitsheader',
            name='airmass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='aptarea',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='aptdia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='ccd_temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='cd1_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='cd1_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='cd2_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='cd2_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='cdelt1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='cdelt2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='crval1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='crval2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='exp_tot',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='exposure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='exptime',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='focallen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='focussz',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='focustem',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='jd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='jd_ave',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='jd_helio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='objctalt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='objctaz',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='objctha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='set_temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='xbinning',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='xpixsz',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='ybinning',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitsheader',
            name='ypixsz',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='cal_offset',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='object',
            name='max_use',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='photometry',
            name='alpha_j2000',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='photometry',
            name='calibrated_magnitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='photometry',
            name='delta_j2000',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='photometry',
            name='fwhm_world',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='photometry',
            name='magnitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='photometry',
            name='magnitude_rms_error',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='photometry',
            name='x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='photometry',
            name='y',
            field=models.FloatField(),
        ),
    ]
